[tool.poetry]
name = "data-quality-workshop"
version = "0.1.0"
description = "ETL project"
authors = ["Raquel Reis <raquelreis233@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.7"
pandas = "^2.2.2"
openpyxl = "^3.1.2"
pytest = "^8.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
